#!/usr/bin/env python3
"""Generate ROM-resident sector-to-linedef lookup tables from a Doom IWAD."""

from __future__ import annotations

import argparse
import struct
from pathlib import Path


MAP_NAMES = tuple(f"E1M{i}" for i in range(1, 10))
MAP_LUMPS = {
    "LINEDEFS": 2,
    "SIDEDEFS": 3,
    "SECTORS": 8,
}


class Wad:
    def __init__(self, path: Path) -> None:
        self.data = path.read_bytes()
        kind, count, directory_offset = struct.unpack_from("<4sII", self.data)
        if kind not in (b"IWAD", b"PWAD"):
            raise ValueError(f"{path}: not a Doom WAD")

        self.lumps: list[tuple[str, int, int]] = []
        for index in range(count):
            offset = directory_offset + index * 16
            file_offset, size, raw_name = struct.unpack_from(
                "<II8s", self.data, offset
            )
            name = raw_name.rstrip(b"\0").decode("ascii")
            self.lumps.append((name, file_offset, size))

    def lump(self, index: int) -> bytes:
        _, offset, size = self.lumps[index]
        return self.data[offset : offset + size]

    def index(self, name: str) -> int:
        return next(i for i, lump in enumerate(self.lumps) if lump[0] == name)


def map_sector_lines(wad: Wad, map_name: str) -> list[list[int]]:
    marker = wad.index(map_name)
    linedefs = wad.lump(marker + MAP_LUMPS["LINEDEFS"])
    sidedefs = wad.lump(marker + MAP_LUMPS["SIDEDEFS"])
    sectors = wad.lump(marker + MAP_LUMPS["SECTORS"])

    if len(linedefs) % 14 or len(sidedefs) % 30 or len(sectors) % 26:
        raise ValueError(f"{map_name}: malformed standard Doom map lumps")

    sector_count = len(sectors) // 26
    side_count = len(sidedefs) // 30
    result: list[list[int]] = [[] for _ in range(sector_count)]

    def side_sector(side_index: int) -> int:
        if side_index < 0 or side_index >= side_count:
            raise ValueError(f"{map_name}: invalid sidedef {side_index}")
        sector = struct.unpack_from("<h", sidedefs, side_index * 30 + 28)[0]
        if sector < 0 or sector >= sector_count:
            raise ValueError(f"{map_name}: invalid sector {sector}")
        return sector

    for line_index in range(len(linedefs) // 14):
        right, left = struct.unpack_from("<hh", linedefs, line_index * 14 + 10)
        front = side_sector(right)
        result[front].append(line_index)

        if left >= 0:
            back = side_sector(left)
            if back != front:
                result[back].append(line_index)

    return result


def format_values(values: list[int], width: int = 12) -> str:
    rows = []
    for start in range(0, len(values), width):
        rows.append("    " + ", ".join(str(value) for value in values[start : start + width]))
    return ",\n".join(rows)


def generate(wad: Wad) -> str:
    all_lines: list[int] = []
    all_spans: list[tuple[int, int]] = []
    maps: list[tuple[int, int]] = []

    for map_name in MAP_NAMES:
        sector_lines = map_sector_lines(wad, map_name)
        line_base = len(all_lines)
        span_base = len(all_spans)
        local_offset = 0

        for lines in sector_lines:
            all_spans.append((local_offset, len(lines)))
            all_lines.extend(lines)
            local_offset += len(lines)

        maps.append((line_base, span_base))

    span_values = [value for span in all_spans for value in span]
    map_values = [value for entry in maps for value in entry]

    return f"""/* Generated by tools/gen_neogeo_sector_lines.py. */
#ifndef DOOM_NEOGEO_SECTOR_LINES_H
#define DOOM_NEOGEO_SECTOR_LINES_H

#include <stdint.h>

#if defined __NGDEVKIT__
#define DOOM_MAP_ROM __attribute__((section(".text2")))
#else
#define DOOM_MAP_ROM
#endif

typedef struct
{{
    uint16_t line_base;
    uint16_t span_base;
}} doom_sector_line_map_t;

DOOM_MAP_ROM
static const uint16_t doom_sector_line_indices[{len(all_lines)}] =
{{
{format_values(all_lines)}
}};

DOOM_MAP_ROM
static const sectorlinespan_t doom_sector_line_spans[{len(all_spans)}] =
{{
{format_values(span_values)}
}};

DOOM_MAP_ROM
static const doom_sector_line_map_t doom_sector_line_maps[{len(maps)}] =
{{
{format_values(map_values, 6)}
}};

#undef DOOM_MAP_ROM
#endif
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--iwad", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    output = generate(Wad(args.iwad))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="ascii")


if __name__ == "__main__":
    main()
